routes/web.php
<?php

use Illuminate\Support\Facades\Route;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', function () {
    return redirect('/posts');
});
Route::get('/', 'PostController@index');
Route::resource('posts','PostController');

/*Поиск записей*/
Route::get('/search','PostController@search');
/*Поиск записей*/
/*контактная форма*/
Route::get('ajax-contact-form', 'AjaxContactController@index');
Route::post('save', 'AjaxContactController@store');
/*контактная форма*/
/*pagination*/

/*pagination*/

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Post extends Model
{
    //use HasFactory;
    protected $fillable = [
        'fio',
        'email',
        'address',
        'image',
        'phone',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        //$posts=Post::all();
        //dd($posts);
        $posts = Post::paginate(3);
        return view('posts.index',compact('posts'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'fio' => 'required',
            'email' => 'required',
            'address' => 'required',
            'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
            'phone' => 'required'
        ]);
        $path = $request->file('image')->store('public/images');
        $post=new Post([
           'fio'=>$request->get('fio'),
           'email'=>$request->get('email'),
           'address'=>$request ->get('address'),
           'image'=>$path,
           'phone'=>$request ->get('phone'),
        ]);

        $post->save();
        return redirect('/posts')->with('success', 'Пост успешно добавлен.');
    }

    /**h
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post=Post::find($id);
        return view('posts.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post=Post::find($id);
        return view('posts.edit',compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $request->validate([
            'fio' => 'required',
            'email' => 'required',
            'address' => 'required',
            'phone' => 'required'
        ]);




        $post = Post::find($id);
        $post->fio =  $request->get('fio');
        $post->email =  $request->get('email');
        $post->address =  $request->get('address');

        if($request->hasFile('image')){
            $request->validate([
                'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
            ]);
            $path = $request->file('image')->store('public/images');
            $post->image = $path;
        }

        $post->phone =  $request->get('phone');
        $post->save();
        return redirect('/posts')->with('success', 'Пост успешно обновлен.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post=Post::find($id);
        $post->delete();
        return redirect('/posts')->with('success', 'Пост успешно удален.');
    }

    public function search(){
        $search_text=$_GET['query'];
        $posts=Post::where('fio','LIKE','%'.$search_text.'%')->orWhere('phone', 'LIKE', '%'.$search_text.'%')->orWhere('address', 'LIKE', '%'.$search_text.'%')->get();
        return view('posts.search',compact('posts'));
    }




}

resources/views/ajax-contact-form.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Form Submit using Ajax jQuery in Laravel 8 with Validation</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
    <style>
        .error{
            color: #FF0000;
        }
    </style>
</head>
<body>
<div class="container mt-4">
    <div class="card">
        <div class="card-header text-center font-weight-bold">
            <h2>Laravel 8 Ajax Form Submit with Validation Example</h2>
        </div>
        <div class="card-body">
            <form name="ajax-contact-form" id="ajax-contact-form" method="post" action="javascript:void(0)">
                @csrf
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text" id="name" name="name" class="form-control">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Email</label>
                    <input type="email" id="email" name="email" class="form-control">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Subject</label>
                    <input type="text" id="subject" name="subject" class="form-control">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Description</label>
                    <textarea name="description" id="description" class="form-control"></textarea>
                </div>
                <button type="submit" class="btn btn-primary" id="submit">Submit</button>
            </form>
        </div>
    </div>
</div>
<script>
    if ($("#ajax-contact-form").length > 0) {
        $("#ajax-contact-form").validate({
            rules: {
                name: {
                    required: true,
                    maxlength: 50
                },
                email: {
                    required: true,
                    maxlength: 50,
                    email: true,
                },
                subject: {
                    required: true,
                    maxlength: 100
                },
                description: {
                    required: true,
                    maxlength: 300
                },
            },
            messages: {
                name: {
                    required: "Please enter name",
                    maxlength: "Your name maxlength should be 50 characters long."
                },
                email: {
                    required: "Please enter valid email",
                    email: "Please enter valid email",
                    maxlength: "The email name should less than or equal to 50 characters",
                },
                subject: {
                    required: "Please enter subject",
                    maxlength: "Your subject maxlength should be 100 characters long."
                },
                description: {
                    required: "Please enter description",
                    maxlength: "Your description name maxlength should be 300 characters long."
                },
            },
            submitHandler: function(form) {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                $('#submit').html('Please Wait...');
                $("#submit"). attr("disabled", true);
                $.ajax({
                    url: "{{url('save')}}",
                    type: "POST",
                    data: $('#ajax-contact-form').serialize(),
                    success: function( response ) {
                        $('#submit').html('Submit');
                        $("#submit"). attr("disabled", false);
                        alert('Ajax form has been submitted successfully');
                        document.getElementById("ajax-contact-form").reset();
                    }
                });
            }
        })
    }
</script>
</body>
</html>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>@yield('fio')</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success mb-3">
        <div class="container">
            <a class="navbar-brand" href="#">Адресная книга</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="http://laravel7-crud/posts">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{route('posts.index')}}">Контакты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="http://laravel7-crud/ajax-contact-form">контактная форма</a>
                    </li>

{{--                    <li class="nav-item dropdown">--}}
{{--                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">--}}
{{--                            Dropdown--}}
{{--                        </a>--}}
{{--                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">--}}
{{--                            <li><a class="dropdown-item" href="#">Action</a></li>--}}
{{--                            <li><a class="dropdown-item" href="#">Another action</a></li>--}}
{{--                            <li><hr class="dropdown-divider"></li>--}}
{{--                            <li><a class="dropdown-item" href="#">Something else here</a></li>--}}
{{--                        </ul>--}}
{{--                    </li>--}}
{{--                    <li class="nav-item">--}}
{{--                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>--}}
{{--                    </li>--}}
                </ul>
                <form class="d-flex" action="{{url('/search')}}" type="get">

                    <input class="form-control me-2" name="query" type="search" placeholder="Поиск контакта" aria-label="Search">
                    <button class="btn btn-primary" type="submit">Поиск</button>
                </form>
            </div>
        </div>
    </nav>
<div class="container">
    @yield('content')
</div>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
-->
<script src="{{asset('js/app.js')}}"></script>
    <script>
        $(function (){
           $('.alert-success').fadeOut(3000);
           $("#phone").mask("+7(999)999-99-99");
        });


    </script>
    <script src="https://cdn.jsdelivr.net/npm/jquery.maskedinput@1.4.1/src/jquery.maskedinput.js" type="text/javascript"></script>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('title', 'Добавить Пост')



@section('content')
    <div class="row">
        <div class="col-lg-6 mx-auto">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Error!</strong>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li></li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{route('posts.store')}}" enctype="multipart/form-data">
                @csrf
                <div class="form-group">
                    <label for="post-title">ФИО</label>
                    <input type="text" class="form-control" value="{{old('fio')}}" name="fio" id="post-fio" placeholder="ФИО">
                </div>
                <div class="form-group">
                    <label for="post-title">Email Почта</label>
                    <input type="email" class="form-control" value="{{old('email')}}" name="email" id="email" placeholder="email">
                </div>
                <div class="form-group">
                    <label for="post-address">Адрес</label>
                    <textarea class="form-control"  name="address" id="post-address" rows="3" placeholder="Адрес Контакта">{{old('address')}}</textarea>
                </div>

                <div class="form-group">
                    <input type="file" name="image" class="form-control">
                </div>

                <div class="form-group">
                    <label for="post-price"  >Номер телефона</label>
                    <input type="text"  class="form-control" name="phone" id="phone" placeholder="номер телефона" value="{{old('phone')}}">
                </div>
                <button type="submit" class="btn btn-success">Добавить Контакт</button>
            </form>
        </div>
    </div>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('title', $post->title)



@section('content')
    <div class="row">
        <div class="col-lg-6 mx-auto">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <strong>Error!</strong>
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li></li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{route('posts.update',$post->id)}}" enctype="multipart/form-data">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label for="post-title">ФИО контакта</label>
                    <input type="text" class="form-control" value="{{$post->fio}}" name="fio" id="post-title" placeholder="ФИО контакта">
                </div>
                <div class="form-group">
                    <label for="post-title">email контакта</label>
                    <input type="text" class="form-control" value="{{$post->email}}" name="email" id="email" placeholder="email">
                </div>
                <div class="form-group">
                    <label for="post-address">Адрес контакта</label>
                    <textarea class="form-control"  name="address" id="post-address" rows="3" placeholder="Адрес контакта">{{$post->address}}</textarea>
                </div>

                <div class="form-group">
                    <input type="file" name="image" class="form-control" placeholder="Post Title">
                    <img src="{{ Storage::url($post->image) }}" height="200" width="200" alt="" />
                </div>


                <div class="form-group">
                    <label for="post-phone">Телефон контакта</label>
                    <input type="text"  class="form-control" name="phone" id="phone" placeholder="номер телефона" value="{{$post->phone}}">
                </div>
                <button type="submit" class="btn btn-success">Редактировать Контакт</button>
            </form>
        </div>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('title', 'Все посты')


@section('content')
    <a href="{{route('posts.create')}}" class="btn btn-success">создать Контакт</a>
    @if (session()->get('success'))
        <div class="alert alert-success mt-3">
            {{session()->get('success')}}
        </div>
    @endif
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ФИО контакта</th>
            <th scope="col">Email</th>
            <th scope="col">Адрес</th>
            <th scope="col">Изображение</th>
            <th scope="col">Номер телефона</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        @if($posts)
        @foreach($posts as $post)
        <tr>
            <th scope="row">{{$post->id}}</th>
            <td>{{$post->fio}}</td>
            <td>{{$post->email}}</td>
            <td>{{$post->address}}</td>
            <td><img src="{{ Storage::url($post->image) }}" height="75" width="75" alt="" /></td>
            <td>{{$post->phone}}</td>
            <td class="table-buttons">
                <a href="{{route('posts.show',$post)}}" class="btn btn-success"><i class="fa fa-eye"></i></a>
                <a href="{{route('posts.edit',$post)}}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                <form action="{{route('posts.destroy',$post)}}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
                </form>

            </td>
        </tr>
        @endforeach
        @else
            <tr>
                <td colspan="3" class="text-danger">Контакты  не найдены.</td>
            </tr>
        @endif
        </tbody>

    </table>
    <div class="d-flex justify-content-center">
        {!! $posts->appends(['sort' => 'department'])->links() !!}
    </div>
@endsection

resources/views/posts/search.blade.php
@extends('layouts.app')

@section('title', 'Все посты')


@section('content')
    <a href="{{route('posts.create')}}" class="btn btn-success">создать Пост</a>
    @if (session()->get('success'))
        <div class="alert alert-success mt-3">
            {{session()->get('success')}}
        </div>
    @endif
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">ФИО</th>
            <th scope="col">Email</th>
            <th scope="col">Адрес контакта</th>
            <th scope="col">Изображение</th>
            <th scope="col">Номер телефона</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        @if($posts)
            @foreach($posts as $post)
                <tr>
                    <th scope="row">{{$post->id}}</th>
                    <td>{{$post->fio}}</td>
                    <td>{{$post->email}}</td>
                    <td>{{$post->address}}</td>
                    <td><img src="{{ Storage::url($post->image) }}" height="75" width="75" alt="" /></td>
                    <td>{{$post->phone}}</td>
                    <td class="table-buttons">
                        <a href="{{route('posts.show',$post)}}" class="btn btn-success"><i class="fa fa-eye"></i></a>
                        <a href="{{route('posts.edit',$post)}}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                        <form action="{{route('posts.destroy',$post)}}" method="post" >
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i></button>
                        </form>

                    </td>
                </tr>
            @endforeach
        @else
            <tr>
                <td colspan="3" class="text-danger">Записи не найдены.</td>
            </tr>
        @endif
        </tbody>
    </table>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('fio',$post->fio)


@section('content')
    <div class="card">
        <div class="card-body">
            <h3>ФИО: {{$post->fio}}</h3>
            <h3>Почта :{{$post->email}}</h3>
            <p>Адрес: {{$post->description}}</p>
            <p><img src="{{ Storage::url($post->image) }}" height="75" width="75" alt="" /></p>
            <p>Номер телефона <b> {{$post->phone}}</b></p>
        </div>
    </div>
@endsection